--Question 1. Write a SQL query to select all the salespeople. Return salesman_id, name, city, 
--commission with the percent sign (%).select salesman_id,name,city,((cast(comission as varchar(4)) +'%')) from salesman--Question 2. Write a SQL query to find the number of orders booked for each day.select order_date,count(order_date) as 'number of orders' from orders group by order_date ---Question 3. Write a SQL query to show all the orders. Sort the result-set in ascending order 
--by ord_no. Return all fields.

select*from orders order by order_date asc

---Question 4. Write a SQL query to show all the customers. Sort the result-set by customer_id. 
--Return cust_name, city, grade.

select customer_name,city,grade from customer order by customer_id

---Question 5. Identify the maximum purchase amount generated by each salesperson for each 
--order date by writing a SQL query. Sort the result set in ascending order by 
--salesperson ID and order date.select salesman_id,max(purch_amt),order_date from orders group by salesman_id,order_date order by salesman_id,order_date asc---Question 6. Create a SQL query that records the number of distinct orders and the maximum 
--purchase amount for every client.

select count(distinct order_no) as 'numbers' ,customer_id,max(purch_amt) as'max purch amount' from orders group by customer_id

